"""migration 002 + 조 스냅샷 계약 정적 감사 (read-only, 실DB/Streamlit 불필요).

이 테스트는 migration 002 의 "DDL 전용 + 자동 백필 금지" 계약을 회귀로 고정한다:
  1) 두 migration SQL 의 정적 불변식 — 파괴적 DDL 없음, 멱등 가드, 그리고
     002 에 데이터 조작(INSERT/UPDATE/DELETE/TRUNCATE)이 전혀 없음.
     특히 users 현재 소속을 과거 편성으로 각인하는 자동 백필이 없어야 한다
     (DDL 만 적용하면 기존 work_schedules 1116건에 assignment 행이 생기지 않는다).
  2) validators 계약이 002 스키마 제약(월 1일, NULL 허용 team/shift, 월중복)과 일치
  3) 근무 조회(work_schedules) 경로가 schedule_assignments 존재에 의존하지 않음
  4) teams(화면의 A/B/C조)와 shift_groups(근무조)의 의미가 저장 경로에서 혼용되지 않음

실행: PYTHONUTF8=1 .venv/Scripts/python.exe scripts/test_migration_002_audit.py
"""
from __future__ import annotations

import inspect
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

os.environ["DUTY_DATA_MODE"] = "sample"

PASS = 0
FAIL: list[str] = []


def check(name: str, cond: bool) -> None:
    global PASS
    if cond:
        PASS += 1
        print(f"  ok - {name}")
    else:
        FAIL.append(name)
        print(f"  FAIL - {name}")


def _strip_sql_comments(sql: str) -> str:
    """라인 주석(--)을 제거해 '실행되는' DDL 만 남긴다(롤백 안내 주석 배제)."""
    out = []
    for line in sql.splitlines():
        idx = line.find("--")
        out.append(line if idx < 0 else line[:idx])
    return "\n".join(out)


MIG = ROOT / "supabase" / "migrations"
SQL1 = (MIG / "001_initial_schema.sql").read_text(encoding="utf-8")
SQL2 = (MIG / "002_schedule_assignments.sql").read_text(encoding="utf-8")
EXEC1 = _strip_sql_comments(SQL1).lower()
EXEC2 = _strip_sql_comments(SQL2).lower()
DATA_TABLES = ("departments", "teams", "users", "work_types", "work_schedules")


# ===== 1) 정적 SQL 불변식 =====
print("migration SQL 정적 불변식")

# 실행 구문에 기존 데이터 테이블을 drop 하는 문장이 없어야 한다(롤백은 주석 안내뿐).
active_drop = any(re.search(rf"drop\s+table\s+(if\s+exists\s+)?(public\.)?{t}\b", EXEC1 + EXEC2)
                  for t in DATA_TABLES)
check("실행 DDL 에 기존 데이터 테이블 DROP 없음(롤백은 주석뿐)", not active_drop)

check("002: schedule_assignments 를 create table if not exists 로 생성",
      "create table if not exists public.schedule_assignments" in EXEC2)
check("002: shift_groups 를 create table if not exists 로 생성",
      "create table if not exists public.shift_groups" in EXEC2)
check("002: work_schedules 는 add column if not exists 만(파괴적 변경 없음)",
      "add column if not exists schedule_assignment_id" in EXEC2
      and "drop column" not in EXEC2 and "alter column" not in EXEC2)

check("002: 직원-월 UNIQUE(user_id, schedule_month)",
      "unique (user_id, schedule_month)" in EXEC2)
check("002: schedule_month 는 월 1일 CHECK",
      "extract(day from schedule_month) = 1" in EXEC2)
check("002: team 은 (team_id, department_id) 복합 FK(teams 소속 보장)",
      "foreign key (team_id, department_id)" in EXEC2
      and "references public.teams(id, department_id)" in EXEC2)
# 스냅샷 무결성: shift_group_code 는 shift_groups 로의 FK 가 아니어야 한다.
check("002: shift_group_code 는 shift_groups FK 아님(기준정보 변경이 과거를 깨지 않음)",
      "references public.shift_groups" not in EXEC2)
check("002: shift_group_code NULL 허용(현재 편성 화면은 근무조 미입력)",
      "shift_group_code text," in EXEC2 and "shift_group_code text not null" not in EXEC2)

# *** 핵심 계약: 002 는 DDL 전용 — 데이터 조작(DML)이 전혀 없어야 한다. ***
# DDL 만 적용하면 기존 work_schedules 행 수·값이 그대로이고 assignment 행도 생기지 않는다.
check("002: INSERT 구문 없음(자동 백필 제거 — 기존 월에 assignment 미생성)",
      re.search(r"\binsert\s+into\b", EXEC2) is None)
check("002: 테이블 UPDATE 구문 없음(schedule_assignment_id 자동 연결 제거)",
      re.search(r"\bupdate\s+public\.", EXEC2) is None
      and re.search(r"(?m)^\s*update\b", EXEC2) is None)
check("001+002: DELETE/TRUNCATE 없음(기존 행 삭제 불가)",
      re.search(r"\b(delete\s+from|truncate)\b", EXEC1 + EXEC2) is None)
check("002: users 현재 소속(u.department_id/u.team_id)을 참조하지 않음(과거 조 추정 금지)",
      "u.department_id" not in EXEC2 and "u.team_id" not in EXEC2
      and "from public.users" not in EXEC2)
check("002: work_schedules 를 데이터 소스로 읽지 않음(DDL 전용)",
      "from public.work_schedules" not in EXEC2)

# RLS: 002 는 001 과 동일 패턴(정책 없이 RLS enable → service_role 로만 접근)
check("002: 신규 테이블 RLS enable(001 과 동일 패턴)",
      "enable row level security" in EXEC2)

# 001↔002 기본 계약 정합 + FK 삭제 정책
check("001+002: 모든 FK 가 on delete restrict(연쇄 삭제/SET NULL 없음)",
      "on delete cascade" not in (EXEC1 + EXEC2)
      and "on delete set null" not in (EXEC1 + EXEC2))
check("002: PK 타입이 001 과 동일(bigint identity)",
      "bigint generated by default as identity primary key" in EXEC2)
check("002: created/updated_at 이 001 과 동일(timestamptz not null default now())",
      EXEC2.count("timestamptz not null default now()") >= 4)
check("002: 롤백 주석이 FK 의존성 역순(제약→인덱스→컬럼→assignments→shift_groups)",
      -1 < SQL2.find("drop constraint if exists work_schedules_assignment_date_key")
      < SQL2.find("drop index if exists work_schedules_assignment_idx")
      < SQL2.find("drop column if exists schedule_assignment_id")
      < SQL2.find("drop table if exists public.schedule_assignments")
      < SQL2.find("drop table if exists public.shift_groups"))
check("002: 기존 데이터 무백필 정책이 SQL 주석에 문서화됨",
      "자동 백필" in SQL2 and "fallback" in SQL2)


# ===== 2) validators 계약 ↔ 002 스키마 제약 정합 =====
print("validators 계약 <-> 002 스키마 정합")
from modules import validators  # noqa: E402

check("normalize_schedule_month((2027,7)) == 2027-07-01 (월 1일 CHECK 정합)",
      validators.normalize_schedule_month((2027, 7)) == "2027-07-01")
check("normalize_schedule_month('2027-07-19') == 2027-07-01",
      validators.normalize_schedule_month("2027-07-19") == "2027-07-01")

emp_nos = {"E1"}
dept_codes = {"D1"}
team_keys = {("D1", "A")}
shift_keys = {("D1", "S1")}

# require_shift=False: 팀/조 미지정 허용(team_id·shift_group_code NULL 허용과 정합)
norm, errs = validators.validate_assignment_records(
    [{"emp_no": "E1", "schedule_month": (2027, 7), "dept_code": "D1",
      "team_code": "", "shift_group_code": ""}],
    emp_nos, dept_codes, team_keys, shift_keys, require_shift=False,
)
check("require_shift=False: 조/팀 미지정 무오류(NULL 허용 정합)", not errs)
check("require_shift=False: schedule_month 월 1일로 정규화", norm[0]["schedule_month"] == "2027-07-01")
check("팀 미지정('')이 그대로 보존됨(users 조 자동 대입/A조 fallback 저장 없음)",
      norm[0]["team_code"] == "")
check("근무조 미지정('')도 그대로 보존됨", norm[0]["shift_group_code"] == "")

# require_shift=True(기본 002 계약): 조 코드 필수
_, errs_req = validators.validate_assignment_records(
    [{"emp_no": "E1", "schedule_month": (2027, 7), "dept_code": "D1",
      "team_code": "A", "shift_group_code": ""}],
    emp_nos, dept_codes, team_keys, shift_keys, require_shift=True,
)
check("require_shift=True: 조 코드 누락 시 오류(기본 002 계약)", any("조 코드" in e for e in errs_req))

# 직원-월 중복 → UNIQUE(user_id, schedule_month) 정합
_, errs_dup = validators.validate_assignment_records(
    [{"emp_no": "E1", "schedule_month": (2027, 7), "dept_code": "D1", "team_code": "A", "shift_group_code": "S1"},
     {"emp_no": "E1", "schedule_month": (2027, 7), "dept_code": "D1", "team_code": "A", "shift_group_code": "S1"}],
    emp_nos, dept_codes, team_keys, shift_keys, require_shift=True,
)
check("같은 직원-월 중복 검출(UNIQUE 정합)", any("중복" in e for e in errs_dup))

# 없는 팀 → 복합 FK 위반을 앱단에서 선차단
_, errs_team = validators.validate_assignment_records(
    [{"emp_no": "E1", "schedule_month": (2027, 7), "dept_code": "D1", "team_code": "Z", "shift_group_code": "S1"}],
    emp_nos, dept_codes, team_keys, shift_keys, require_shift=True,
)
check("부서에 없는 팀 선차단(복합 FK 방어)", any("없는 팀" in e for e in errs_team))


# ===== 3) 근무 조회는 schedule_assignments 에 의존하지 않음 =====
print("근무 조회(work_schedules) 독립성")
from modules import supabase_repository as repo  # noqa: E402
from modules import db  # noqa: E402

for fn in (repo.get_month_schedules, repo.get_user_schedules, repo._schedule_rows):
    src = inspect.getsource(fn)
    check(f"repo.{fn.__name__} 소스가 schedule_assignments 를 조회하지 않음",
          "schedule_assignments" not in src and "shift_groups" not in src)

# sample 모드: 편성 없는 월도 예외 없이 빈 편성 반환(오류를 빈 DF 로 위장하지 않음 — 정상 빈월)
empty_assign = db.get_month_assignments(2031, 3)
check("빈 월 편성 조회는 예외 없이 빈 계약 반환", empty_assign.empty)

# sample 모드: work_schedules 조회는 편성 유무와 무관하게 동작
sched = db.get_month_schedules([str(e).strip() for e in db.get_users()["emp_no"]], 2026, 7)
check("근무 조회는 편성 테이블과 무관하게 동작(계약 컬럼 유지)",
      list(sched.columns) == db.SCHEDULE_COLUMNS)


# ===== 4) 편성 화면의 조 = 자유 입력 근무조 스냅샷 (2026-08-07 계약) =====
# 구 계약(조=teams 기준정보 검증, shift_group_code 항상 빈 값)은 2026-08-07 사용자
# 결정으로 폐기됐다: A/B/C조는 기준정보에서 빠지고 편성표에서 직접 입력한다.
print("편성 화면 조 축 계약 (자유 입력 근무조 스냅샷, 소스 정적 검사)")
EDIT_SRC = (ROOT / "views" / "schedule_edit.py").read_text(encoding="utf-8")

# 화면의 "조"는 자유 입력이며 normalize_shift_group 으로 정규화해 스냅샷으로 저장한다.
check("편성 화면이 근무조 정규화(normalize_shift_group)를 정의·사용",
      "def normalize_shift_group" in EDIT_SRC
      and "normalize_shift_group(team_txt)" in EDIT_SRC)
check("편성 저장이 정규화된 근무조를 shift_group_code 로 넘김",
      '"shift_group_code": shift_code' in EDIT_SRC)
check("편성 저장이 require_shift=False 를 사용(근무조가 저장을 차단하지 않음)",
      "require_shift=False" in EDIT_SRC)
check("편성 화면이 조를 기준정보(shift_groups)로 검증하지 않음",
      "get_shift_groups" not in EDIT_SRC)
check("저장 후 세션 캐시에 근무조 스냅샷 포함(재조회 시 조 표시 유지)",
      '"shift_group_code": rec["shift_group_code"]' in EDIT_SRC)
# assignment 실패를 성공으로 표시하지 않는 플래그 계약
check("assignment 영속 실패를 성공 메시지로 숨기지 않음(assign_persisted 분기)",
      "assign_persisted = False" in EDIT_SRC and "assign_persisted = True" in EDIT_SRC)


print()
if FAIL:
    print(f"FAILED {len(FAIL)}: {FAIL}")
    sys.exit(1)
print(f"ALL PASSED ({PASS} checks)")
