-- Initial schema for a clean workops Supabase test project.
-- Review existing tables before applying this file. It never drops a table or data row.

create table if not exists public.departments (
    id bigint generated by default as identity primary key,
    dept_code text not null unique,
    dept_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint departments_code_not_blank check (btrim(dept_code) <> ''),
    constraint departments_name_not_blank check (btrim(dept_name) <> '')
);

create table if not exists public.teams (
    id bigint generated by default as identity primary key,
    department_id bigint not null references public.departments(id) on delete restrict,
    team_code text not null,
    team_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint teams_department_code_key unique (department_id, team_code),
    constraint teams_id_department_key unique (id, department_id),
    constraint teams_code_not_blank check (btrim(team_code) <> ''),
    constraint teams_name_not_blank check (btrim(team_name) <> '')
);

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    emp_no text not null unique,
    name text not null,
    department_id bigint not null references public.departments(id) on delete restrict,
    team_id bigint,
    position text not null default '',
    role text not null default 'USER',
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint users_team_department_fk foreign key (team_id, department_id)
        references public.teams(id, department_id) on delete restrict,
    constraint users_emp_no_not_blank check (btrim(emp_no) <> ''),
    constraint users_name_not_blank check (btrim(name) <> ''),
    constraint users_role_check check (role in ('ADMIN', 'MANAGER', 'USER'))
);

create table if not exists public.work_types (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    category text not null,
    short_label text not null,
    start_time time,
    end_time time,
    color text,
    is_work boolean not null default true,
    affects_allowance boolean not null default false,
    description text not null default '',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint work_types_code_not_blank check (btrim(code) <> ''),
    constraint work_types_name_not_blank check (btrim(name) <> ''),
    constraint work_types_category_not_blank check (btrim(category) <> ''),
    constraint work_types_short_label_not_blank check (btrim(short_label) <> '')
);

create table if not exists public.work_schedules (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete restrict,
    work_date date not null,
    work_type_code text not null references public.work_types(code) on delete restrict on update restrict,
    note text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint work_schedules_user_date_key unique (user_id, work_date)
);

create index if not exists teams_department_idx on public.teams(department_id);
create index if not exists users_department_team_idx on public.users(department_id, team_id);
create index if not exists users_active_idx on public.users(is_active);
create index if not exists work_schedules_date_idx on public.work_schedules(work_date);
create index if not exists work_schedules_type_idx on public.work_schedules(work_type_code);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists departments_set_updated_at on public.departments;
create trigger departments_set_updated_at
before update on public.departments
for each row execute function public.set_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists work_types_set_updated_at on public.work_types;
create trigger work_types_set_updated_at
before update on public.work_types
for each row execute function public.set_updated_at();

drop trigger if exists work_schedules_set_updated_at on public.work_schedules;
create trigger work_schedules_set_updated_at
before update on public.work_schedules
for each row execute function public.set_updated_at();

alter table public.departments enable row level security;
alter table public.teams enable row level security;
alter table public.users enable row level security;
alter table public.work_types enable row level security;
alter table public.work_schedules enable row level security;

comment on table public.departments is 'Duty scheduler departments; server-side service role access only until production RLS policies are defined.';
comment on table public.teams is 'Duty scheduler teams; server-side service role access only until production RLS policies are defined.';
comment on table public.users is 'Duty scheduler employee master data, not Supabase Auth users.';
comment on table public.work_types is 'Duty scheduler work type master data.';
comment on table public.work_schedules is 'One work type per user and work date.';
