-- 002: Shift group master data + per-employee monthly assignment snapshots.
-- Adds shift_groups / schedule_assignments and links work_schedules to assignments.
-- Never drops a table, never deletes or overwrites existing data rows.
-- Safe to re-run: every statement is guarded (if not exists / on conflict do nothing).
--
-- Partial-failure note: statements are ordered so that each one only depends on
-- earlier ones. Re-running the whole file after a partial failure completes the
-- remaining steps without duplicating anything.
--
-- Manual rollback (reverse order; keeps all pre-002 data intact):
--   alter table public.work_schedules drop constraint if exists work_schedules_assignment_date_key;
--   alter table public.work_schedules drop constraint if exists work_schedules_assignment_user_fk;
--   drop index if exists work_schedules_assignment_idx;
--   alter table public.work_schedules drop column if exists schedule_assignment_id;
--   drop table if exists public.schedule_assignments;
--   drop table if exists public.shift_groups;

-- 근무조 기준정보. 선택지 제공과 저장 전 유효성 검사 전용.
create table if not exists public.shift_groups (
    id bigint generated by default as identity primary key,
    department_id bigint not null references public.departments(id) on delete restrict,
    shift_code text not null,
    shift_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint shift_groups_department_code_key unique (department_id, shift_code),
    constraint shift_groups_code_not_blank check (btrim(shift_code) <> ''),
    constraint shift_groups_name_not_blank check (btrim(shift_name) <> '')
);

-- 직원별 월 편성 스냅샷. 부서·팀은 관계값(id), 조는 당시 코드 텍스트 스냅샷.
-- shift_group_code에 shift_groups FK를 걸지 않는다: 조 기준정보의 수정·중지·삭제가
-- 과거 월 편성을 깨면 안 된다. 유효성은 앱 저장 계층에서 검사한다.
-- shift_group_code가 NULL 허용인 이유: 기존 work_schedules backfill 시 당시 조를
-- 알 수 없다. 신규 저장 경로에서는 앱 검증이 조 코드를 필수로 요구한다.
create table if not exists public.schedule_assignments (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete restrict,
    schedule_month date not null,
    department_id bigint not null references public.departments(id) on delete restrict,
    team_id bigint,
    shift_group_code text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint schedule_assignments_user_month_key unique (user_id, schedule_month),
    constraint schedule_assignments_id_user_key unique (id, user_id),
    constraint schedule_assignments_month_first_day check (extract(day from schedule_month) = 1),
    constraint schedule_assignments_team_department_fk foreign key (team_id, department_id)
        references public.teams(id, department_id) on delete restrict,
    constraint schedule_assignments_shift_code_not_blank
        check (shift_group_code is null or btrim(shift_group_code) <> '')
);

-- work_schedules 과도기 확장: user_id를 유지한 채 편성 연결 컬럼을 추가한다.
-- (schedule_assignment_id, user_id) 복합 FK가 "근무 행의 사용자 ≠ 편성 행의 사용자"
-- 불일치를 DB 수준에서 차단한다. 화면 전환 완료 후 별도 migration에서
-- schedule_assignment_id NOT NULL 승격 + user_id 제거를 진행한다 (docs/database.md §5.2).
alter table public.work_schedules
    add column if not exists schedule_assignment_id bigint;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'work_schedules_assignment_user_fk'
          and conrelid = 'public.work_schedules'::regclass
    ) then
        alter table public.work_schedules
            add constraint work_schedules_assignment_user_fk
            foreign key (schedule_assignment_id, user_id)
            references public.schedule_assignments(id, user_id) on delete restrict;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'work_schedules_assignment_date_key'
          and conrelid = 'public.work_schedules'::regclass
    ) then
        alter table public.work_schedules
            add constraint work_schedules_assignment_date_key
            unique (schedule_assignment_id, work_date);
    end if;
end $$;

create index if not exists shift_groups_department_idx
    on public.shift_groups(department_id);
create index if not exists schedule_assignments_month_idx
    on public.schedule_assignments(schedule_month);
create index if not exists schedule_assignments_department_month_idx
    on public.schedule_assignments(department_id, schedule_month);
create index if not exists work_schedules_assignment_idx
    on public.work_schedules(schedule_assignment_id);

-- updated_at 트리거 (001의 public.set_updated_at 재사용)
drop trigger if exists shift_groups_set_updated_at on public.shift_groups;
create trigger shift_groups_set_updated_at
before update on public.shift_groups
for each row execute function public.set_updated_at();

drop trigger if exists schedule_assignments_set_updated_at on public.schedule_assignments;
create trigger schedule_assignments_set_updated_at
before update on public.schedule_assignments
for each row execute function public.set_updated_at();

alter table public.shift_groups enable row level security;
alter table public.schedule_assignments enable row level security;

-- Backfill: 기존 work_schedules 행이 있으면 (user_id, 해당 월) 편성을 생성해 연결한다.
-- 당시 부서·팀은 알 수 없으므로 users의 현재 소속을 최선값으로 사용하고,
-- 조 코드는 알 수 없으므로 NULL 스냅샷으로 둔다 (이후 화면에서 보완).
-- on conflict do nothing + null 조건 update 이므로 재실행해도 기존 값을 덮지 않는다.
insert into public.schedule_assignments (user_id, schedule_month, department_id, team_id)
select distinct
       ws.user_id,
       date_trunc('month', ws.work_date)::date,
       u.department_id,
       u.team_id
from public.work_schedules ws
join public.users u on u.id = ws.user_id
where ws.schedule_assignment_id is null
on conflict (user_id, schedule_month) do nothing;

update public.work_schedules ws
set schedule_assignment_id = sa.id
from public.schedule_assignments sa
where ws.schedule_assignment_id is null
  and sa.user_id = ws.user_id
  and sa.schedule_month = date_trunc('month', ws.work_date)::date;

comment on table public.shift_groups is
    'Duty scheduler shift group (근무조) master data; select options and validation only — no FK from snapshots.';
comment on table public.schedule_assignments is
    'Per-employee monthly assignment snapshot: department/team relation values plus shift group code snapshot.';
comment on column public.schedule_assignments.shift_group_code is
    'Shift group code snapshot at scheduling time; intentionally not a FK so master changes never break history.';
comment on column public.work_schedules.schedule_assignment_id is
    'Transitional link to schedule_assignments; user_id stays until views migrate (composite FK keeps both consistent).';
