-- 002: Shift group master data + per-employee monthly assignment snapshots.
-- DDL ONLY: adds shift_groups / schedule_assignments and the transitional link
-- column work_schedules.schedule_assignment_id. It reads and writes NO data rows —
-- no INSERT/UPDATE/DELETE on any table. Existing work_schedules rows stay untouched
-- and unlinked (schedule_assignment_id stays NULL for them).
-- Never drops a table, never deletes or overwrites existing data rows.
-- Safe to re-run: every statement is guarded (if not exists / conditional do-block).
--
-- Partial-failure note: statements are ordered so that each one only depends on
-- earlier ones. Re-running the whole file after a partial failure completes the
-- remaining steps without duplicating anything.
--
-- Manual rollback (reverse order; keeps all pre-002 data intact):
--   alter table public.work_schedules drop constraint if exists work_schedules_assignment_date_key;
--   alter table public.work_schedules drop constraint if exists work_schedules_assignment_user_fk;
--   drop index if exists work_schedules_assignment_idx;
--   alter table public.work_schedules drop column if exists schedule_assignment_id;
--   drop table if exists public.schedule_assignments;
--   drop table if exists public.shift_groups;

-- 근무조 기준정보. 선택지 제공과 저장 전 유효성 검사 전용.
create table if not exists public.shift_groups (
    id bigint generated by default as identity primary key,
    department_id bigint not null references public.departments(id) on delete restrict,
    shift_code text not null,
    shift_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint shift_groups_department_code_key unique (department_id, shift_code),
    constraint shift_groups_code_not_blank check (btrim(shift_code) <> ''),
    constraint shift_groups_name_not_blank check (btrim(shift_name) <> '')
);

-- 직원별 월 편성 스냅샷. 부서·팀은 관계값(id) — "월별 배정 스냅샷"이지 당시 명칭
-- 문자열 보존이 아니다(부서명·조명 변경 시 과거 화면도 최신 명칭으로 표시된다).
-- 화면의 A/B/C조는 teams 기준정보(team_id)로 저장한다. shift_group_code(근무조)는
-- 별개 개념의 텍스트 스냅샷이며 shift_groups FK를 걸지 않는다: 근무조 기준정보의
-- 수정·중지·삭제가 과거 월 편성을 깨면 안 된다. 유효성은 앱 저장 계층에서 검사한다.
-- shift_group_code·team_id가 NULL 허용인 이유: (a) 현재 편성 화면은 근무조 입력
-- 없이 부서·팀 스냅샷만 저장하고(validators require_shift=False), 조 미지정 사용자도
-- 있다. (b) 기존 월은 assignment 자체를 만들지 않으므로 백필용 NULL 이 아니라
-- 신규 저장 경로의 선택 입력을 위한 NULL 이다.
create table if not exists public.schedule_assignments (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete restrict,
    schedule_month date not null,
    department_id bigint not null references public.departments(id) on delete restrict,
    team_id bigint,
    shift_group_code text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint schedule_assignments_user_month_key unique (user_id, schedule_month),
    constraint schedule_assignments_id_user_key unique (id, user_id),
    constraint schedule_assignments_month_first_day check (extract(day from schedule_month) = 1),
    constraint schedule_assignments_team_department_fk foreign key (team_id, department_id)
        references public.teams(id, department_id) on delete restrict,
    constraint schedule_assignments_shift_code_not_blank
        check (shift_group_code is null or btrim(shift_group_code) <> '')
);

-- work_schedules 과도기 확장: user_id를 유지한 채 편성 연결 컬럼을 추가한다.
-- (schedule_assignment_id, user_id) 복합 FK가 "근무 행의 사용자 ≠ 편성 행의 사용자"
-- 불일치를 DB 수준에서 차단한다. 화면 전환 완료 후 별도 migration에서
-- schedule_assignment_id NOT NULL 승격 + user_id 제거를 진행한다 (docs/database.md §5.2).
alter table public.work_schedules
    add column if not exists schedule_assignment_id bigint;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'work_schedules_assignment_user_fk'
          and conrelid = 'public.work_schedules'::regclass
    ) then
        alter table public.work_schedules
            add constraint work_schedules_assignment_user_fk
            foreign key (schedule_assignment_id, user_id)
            references public.schedule_assignments(id, user_id) on delete restrict;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'work_schedules_assignment_date_key'
          and conrelid = 'public.work_schedules'::regclass
    ) then
        alter table public.work_schedules
            add constraint work_schedules_assignment_date_key
            unique (schedule_assignment_id, work_date);
    end if;
end $$;

create index if not exists shift_groups_department_idx
    on public.shift_groups(department_id);
create index if not exists schedule_assignments_month_idx
    on public.schedule_assignments(schedule_month);
create index if not exists schedule_assignments_department_month_idx
    on public.schedule_assignments(department_id, schedule_month);
create index if not exists work_schedules_assignment_idx
    on public.work_schedules(schedule_assignment_id);

-- updated_at 트리거 (001의 public.set_updated_at 재사용)
drop trigger if exists shift_groups_set_updated_at on public.shift_groups;
create trigger shift_groups_set_updated_at
before update on public.shift_groups
for each row execute function public.set_updated_at();

drop trigger if exists schedule_assignments_set_updated_at on public.schedule_assignments;
create trigger schedule_assignments_set_updated_at
before update on public.schedule_assignments
for each row execute function public.set_updated_at();

alter table public.shift_groups enable row level security;
alter table public.schedule_assignments enable row level security;

-- ============================================================================
-- 기존 데이터 정책: 자동 백필 없음 (2026-07-16 read-only 감사 결정)
-- ============================================================================
-- 이 migration 은 기존 work_schedules 행에 대해 schedule_assignments 를 생성하지
-- 않고 schedule_assignment_id 도 채우지 않는다. 초기 버전에 있던 자동 백필
-- (users 현재 소속 기반 INSERT + UPDATE 연결)은 제거되었다.
--   제거 이유: 과거 월의 실제 편성 조(A/B/C)를 알 수 있는 신뢰 가능한 원본이
--   DB 에 없다. users 의 "현재" 소속(감사 시점 재직자 대부분 A조)으로 채우면
--   잘못된 과거 편성이 영속 각인된다.
-- 정책:
--   * 기존 월(예: 2026-07, 2027-07)은 assignment 미존재 상태로 유지한다.
--   * 조회 화면은 assignment 가 없으면 users 현재 소속을 표시용으로만 fallback
--     한다 — fallback 값을 스냅샷으로 저장하지 않는다.
--   * assignment 는 편성 화면에서 사용자가 명시적으로 저장한 월부터만 생성된다.
--   * 과거 월의 정확한 조 복구는 명시적 (사번, 월, 부서, 조) 매핑 원본(예: 원본
--     Excel)이 확보된 뒤, 이 migration 과 무관한 별도 승인 스크립트로만 수행한다.
--     dry-run·검증(사번/부서/조 존재, 중복 매핑, 대상 월·인원 사전 출력) 없이
--     실행해서는 안 된다.

comment on table public.shift_groups is
    'Duty scheduler shift group (근무조) master data; select options and validation only — no FK from snapshots.';
comment on table public.schedule_assignments is
    'Per-employee monthly assignment snapshot: department/team relation values plus shift group code snapshot.';
comment on column public.schedule_assignments.shift_group_code is
    'Shift group code snapshot at scheduling time; intentionally not a FK so master changes never break history.';
comment on column public.work_schedules.schedule_assignment_id is
    'Transitional link to schedule_assignments; user_id stays until views migrate (composite FK keeps both consistent).';
