-- 004: 조직 그룹 테이블화 — organization_groups 신설 + departments.group_id FK.
--
-- 목적 (사용자 승인된 DB 구조 변경):
--   003 의 "부서그룹 = departments.department_group/group_sort_order 컬럼" 모델을
--   폐기하고, 그룹을 별도 1급 테이블(organization_groups)로 승격한다.
--   내부 관계를 코드 문자열이 아니라 ID/FK 로 표현한다:
--     organization_groups(id) ─< departments(group_id) ─< teams(department_id)
--
-- 안전 계약:
--   * 어떤 테이블도 drop 하지 않고, 기존 행을 삭제하거나 기존 값을 덮어쓰지 않는다.
--   * group_id 는 신규 컬럼이며 백필(insert+update)로만 채운다.
--   * 재실행 안전: 모든 문장이 guarded (if not exists / on conflict do nothing / group_id is null).
--   * 003 적용/미적용 양쪽에서 동작한다 (백필은 dept_code 기준 — 003 컬럼에 의존하지 않음).
--   * work_schedules / schedule_assignments 는 참조하지 않는다 (근무 데이터 무변경).
--
-- 적용 전후 예상 행 수 (2026-07-22 read-only probe 기준 테스트 프로젝트):
--   departments 5 · teams 6 · users 21 — 세 테이블 행 수 불변 (컬럼만 추가).
--   organization_groups: 0 → 4 (승인된 명시적 그룹 PET/PVC/DECO/ADMIN).
--   실행 DML: organization_groups INSERT 4건 + departments UPDATE 5건(group_id).
--            DELETE 없음. 기존 컬럼 UPDATE 없음.
--
-- 승인된 부서→그룹 매핑 (그룹 4개만 생성; MTRL 은 그룹이 아니라 PET 그룹 소속 부서):
--   group PET   (sort 1)             ← dept PET, dept MTRL(PET원료실)
--   group PVC   (sort 2)             ← dept PVC
--   group DECO  (sort 3)             ← dept DECO
--   group ADMIN (name=관리, sort 999) ← dept ADMIN  (화면 계층에서 삭제/미사용 보호)
--   dept→group: PET→PET, MTRL→PET, PVC→PVC, DECO→DECO, ADMIN→ADMIN.
--
-- 미결정(이 migration 범위 밖 — 별도 후속 migration 으로 분리):
--   * departments.group_id NOT NULL 승격 — 앱 코드가 group_id 를 쓰도록 전환한 뒤 005 에서.
--   * 003 의 department_group/group_sort_order 컬럼 물리 제거 — 앱이 더 이상 읽지 않게 된 뒤.
--   * unit_type / display_order 는 003 소유 컬럼이라 여기서 되돌리거나 재정의하지 않는다
--     (미적용 환경 호환을 위해 add column if not exists 로만 함께 보정한다).
--
-- 수동 롤백 (역순; 004 이전 데이터는 그대로 유지):
--   alter table public.departments drop constraint if exists departments_group_fk;
--   drop index if exists public.departments_group_idx;
--   alter table public.departments drop column if exists group_id;
--   alter table public.departments drop column if exists description;
--   alter table public.teams drop column if exists description;
--   drop table if exists public.organization_groups;   -- group_id FK 제거 후에만 성공
--   -- unit_type/display_order 는 003 소유 — 004 롤백에서 건드리지 않는다.

-- =========================================================================
-- 1) organization_groups — 조직 그룹 1급 테이블
-- =========================================================================
create table if not exists public.organization_groups (
    id bigint generated by default as identity primary key,
    group_code text not null unique,
    group_name text not null,
    sort_order integer not null default 0,
    description text not null default '',
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint organization_groups_code_not_blank check (btrim(group_code) <> ''),
    constraint organization_groups_name_not_blank check (btrim(group_name) <> '')
);

drop trigger if exists organization_groups_set_updated_at on public.organization_groups;
create trigger organization_groups_set_updated_at
before update on public.organization_groups
for each row execute function public.set_updated_at();

alter table public.organization_groups enable row level security;

comment on table public.organization_groups is
    'Organization groups (그룹). First-class table replacing the 003 departments.department_group column model. Server-side service role access only until production RLS.';
comment on column public.organization_groups.group_code is
    'Natural key of the group (unique). Referenced by departments.group_id via id/FK, not by this text.';
comment on column public.organization_groups.sort_order is
    'Global display order of the group.';

-- =========================================================================
-- 2) departments: group_id FK (→ organization_groups) + description
-- =========================================================================
alter table public.departments add column if not exists group_id bigint;
alter table public.departments add column if not exists description text not null default '';

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'departments_group_fk'
          and conrelid = 'public.departments'::regclass
    ) then
        alter table public.departments
            add constraint departments_group_fk
            foreign key (group_id) references public.organization_groups(id)
            on delete restrict;
    end if;
end $$;

create index if not exists departments_group_idx on public.departments(group_id);

comment on column public.departments.group_id is
    'FK to organization_groups(id). Nullable until backfill + app cutover complete (NOT NULL deferred to a later migration).';
comment on column public.departments.description is 'Free-form department note (비고).';

-- =========================================================================
-- 3) teams: description + (003 호환) unit_type
--    department_id FK 는 001 에서 이미 존재 — 유지한다.
-- =========================================================================
alter table public.teams add column if not exists description text not null default '';
alter table public.teams add column if not exists unit_type text not null default 'SHIFT';

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'teams_unit_type_check'
          and conrelid = 'public.teams'::regclass
    ) then
        alter table public.teams
            add constraint teams_unit_type_check
            check (unit_type in ('SHIFT', 'GENERAL'));
    end if;
end $$;

comment on column public.teams.description is 'Free-form operating-unit note (비고).';
comment on column public.teams.unit_type is
    'Operating unit type: SHIFT(교대조 A/B/C) or GENERAL(일반근무). Owned by 003; re-added here if missing for compatibility.';

-- =========================================================================
-- 4) users: display_order (003 호환 — 그룹 내 직원 표시순서)
-- =========================================================================
alter table public.users add column if not exists display_order integer;

comment on column public.users.display_order is
    'Employee display order within the group. Owned by 003; re-added here if missing. NULL = unassigned.';

-- =========================================================================
-- 5) 백필 — 승인된 명시적 4그룹 매핑으로 organization_groups 채우고 group_id 연결.
--    (부서 1개=그룹 1개 자동 생성/런타임 003 감지 방식 폐기. 그룹은 PET/PVC/DECO/ADMIN
--     4개만 생성한다. MTRL 은 그룹이 아니라 PET 그룹 소속 부서다.)
--    무손실: 기존 부서/조/사용자/근무표 행을 수정·삭제하지 않는다. 신규 컬럼 group_id 만 채운다.
--    재실행 안전: on conflict do nothing + where group_id is null → 재실행 시 no-op.
--    ADMIN 그룹 보호(삭제/미사용 차단)는 화면 계층 책임이다 — migration 은 group_code='ADMIN'
--    생성만 하고 DB 보호 컬럼/제약을 추가하지 않는다.
-- =========================================================================

-- 5-1) 승인된 그룹 4건 생성 (group_name/sort_order 명시). 재실행 시 충돌은 무시.
insert into public.organization_groups (group_code, group_name, sort_order) values
    ('PET',   'PET',  1),
    ('PVC',   'PVC',  2),
    ('DECO',  'DECO', 3),
    ('ADMIN', '관리', 999)
on conflict (group_code) do nothing;

-- 5-2) 부서 group_id 연결 — dept_code→group_code 명시 매핑(VALUES 조인).
--      기존 컬럼값은 건드리지 않고 신규 group_id 가 비어 있는(NULL) 행만 채운다.
update public.departments d
   set group_id = g.id
  from public.organization_groups g,
       (values
           ('PET',   'PET'),
           ('MTRL',  'PET'),
           ('PVC',   'PVC'),
           ('DECO',  'DECO'),
           ('ADMIN', 'ADMIN')
       ) as m(dept_code, group_code)
 where d.dept_code = m.dept_code
   and g.group_code = m.group_code
   and d.group_id is null;

-- 검증용(선택, read-only): 백필 후 group_id 미연결 부서가 없어야 한다.
--   select dept_code from public.departments where group_id is null;   -- 기대 0행
