-- 006: 아차사고(near-miss) 보고 — near_miss_reports 테이블 + users.is_safety_officer.
--
-- 목적 (사용자 승인 전 DRAFT — 실행/원격 write 금지, Codex 감사 + 사용자 승인 게이트):
--   신규 기능 "아차사고 보고서 제출 → 평가 → 조회/통계"의 데이터 기반.
--   보고자가 등급을 제안(proposed_grade)하고 평가자(안전담당자/관리자)가 등급을
--   확정(confirmed_grade)한다. 사진은 Supabase Storage 경로 배열(photo_paths)로만
--   보관하고(바이너리는 DB 에 넣지 않음), 통계는 등급/부서/기간/원인/상태로 집계한다.
--
-- 번호 정합 (docs/database.md §7):
--   005(가칭)은 004 후속 정리(departments.group_id NOT NULL 승격 + 003 잔여 그룹
--   컬럼 제거)로 문서에 이미 예약되어 있다. 따라서 아차사고는 004 후속이 아닌
--   독립 기능이므로 005 를 건너뛰고 006 으로 번호를 부여한다.
--
-- 안전 계약 (001/004 관행 준수):
--   * 어떤 테이블도 drop 하지 않고 기존 행/값을 삭제·덮어쓰지 않는다.
--   * 재실행 안전: 모든 문장이 guarded (create table/index if not exists,
--     add column if not exists, do-block 으로 제약 존재 확인 후 추가).
--   * 기존 5개 테이블(001)·조직(004) 데이터를 참조만 하고 수정하지 않는다.
--     users.is_safety_officer 만 신규 컬럼으로 추가하며 기본값 false 로 채워진다.
--   * RLS 는 enable 하되 policy 는 두지 않는다(service role 서버 접근만 — 001/004 관행).
--
-- 수동 롤백 (역순; 006 이전 데이터 유지):
--   drop table if exists public.near_miss_reports;
--   alter table public.users drop column if exists is_safety_officer;

-- =========================================================================
-- 1) users: is_safety_officer — 안전담당자 지정 플래그
--    (평가 권한 능력의 원천. can_evaluate_near_miss = ADMIN|MANAGER|안전담당자)
-- =========================================================================
alter table public.users add column if not exists is_safety_officer boolean not null default false;

comment on column public.users.is_safety_officer is
    'Safety-officer designation (안전담당자). Grants near-miss evaluation capability in addition to ADMIN/MANAGER roles. Read by the app permission helper; NULL 불가(기본 false).';

-- =========================================================================
-- 2) near_miss_reports — 아차사고 보고서
-- =========================================================================
create table if not exists public.near_miss_reports (
    id bigint generated by default as identity primary key,

    -- report_no: 연월(YYYYMM) + 월별 순번(zero-pad). 예: '202607-0007'.
    --   충돌 안전(collision-safe) 생성: 애플리케이션이 대상 연월의 기존 최대 순번
    --   +1 로 계산하되, 아래 unique 제약을 최종 방어선으로 삼아 동시 삽입이 같은
    --   번호를 만들면 unique_violation 을 받고 순번을 재계산해 재시도한다. (진짜
    --   원자적 채번은 전용 시퀀스/카운터 테이블 또는 RPC 가 필요 — 후속 승인 범위.)
    report_no text not null unique,

    work_name text not null,                              -- 작업명(제목)
    work_content text not null default '',                -- 작업 내용
    incident_content text not null default '',            -- 아차사고 내용
    countermeasure text not null default '',              -- 대책/개선안
    site_description text not null default '',             -- 현장/상황 설명

    -- 등급: 보고자 제안(proposed) vs 평가자 확정(confirmed). 둘 다 S~D.
    proposed_grade text,                                  -- 보고자 제안(nullable)
    confirmed_grade text,                                 -- 평가자 확정(평가 후에만)

    -- 사람/조직 관계값(ID/FK). 화면 자연키(emp_no/dept_code)는 파사드에서 조인.
    reporter_user_id bigint not null references public.users(id) on delete restrict,
    evaluator_user_id bigint references public.users(id) on delete restrict,
    department_id bigint references public.departments(id),  -- 보고 시점 부서 귀속(그룹 저장 안 함)

    -- 원인: 통제된 코드 + 자유서술.
    --   코드 집합: JAM(끼임) FALL(추락) DROP(낙하) HIT(충돌) SLIP(전도/미끄러짐)
    --             BURN(화상) PINCH(협착) ETC(기타)
    cause_code text not null,
    cause_detail text not null default '',

    incident_date date not null,                          -- 사고 발생일(기간 통계는 이 값 기준, created_at 아님)

    photo_paths jsonb not null default '[]'::jsonb,       -- Supabase Storage 경로 배열(바이너리 미저장)

    status text not null default 'SUBMITTED',
    rejection_reason text,                                -- 반려 사유(REJECTED 일 때)
    evaluated_at timestamptz,                             -- 평가 확정 시각

    is_active boolean not null default true,              -- 보존(archival)용 — 철회/반려는 상태로 표현하며 이 플래그가 아님

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,

    constraint near_miss_work_name_not_blank
        check (btrim(work_name) <> ''),
    constraint near_miss_proposed_grade_check
        check (proposed_grade is null or proposed_grade in ('S','A','B','C','D')),
    constraint near_miss_confirmed_grade_check
        check (confirmed_grade is null or confirmed_grade in ('S','A','B','C','D')),
    constraint near_miss_cause_code_check
        check (cause_code in ('JAM','FALL','DROP','HIT','SLIP','BURN','PINCH','ETC')),
    constraint near_miss_status_check
        check (status in ('SUBMITTED','IN_REVIEW','EVALUATED','CLOSED','REJECTED')),
    constraint near_miss_photo_paths_is_array
        check (jsonb_typeof(photo_paths) = 'array'),
    -- 평가 필드 3종(확정등급·평가자·평가시각)은 상태가 EVALUATED/CLOSED 일 때만
    -- 모두 존재하고, 그 외 상태에서는 모두 비어 있어야 한다(부분 평가 상태 방지).
    constraint near_miss_eval_consistency check (
        case
            when status in ('EVALUATED','CLOSED')
                then confirmed_grade is not null
                     and evaluator_user_id is not null
                     and evaluated_at is not null
            else confirmed_grade is null
                 and evaluator_user_id is null
                 and evaluated_at is null
        end
    ),
    -- 반려 상태는 사유를 요구한다(반려 semantics).
    constraint near_miss_rejection_reason check (
        status <> 'REJECTED' or btrim(coalesce(rejection_reason, '')) <> ''
    )
);

drop trigger if exists near_miss_reports_set_updated_at on public.near_miss_reports;
create trigger near_miss_reports_set_updated_at
before update on public.near_miss_reports
for each row execute function public.set_updated_at();

alter table public.near_miss_reports enable row level security;

comment on table public.near_miss_reports is
    'Near-miss (아차사고) reports: reporter proposes grade, evaluator (ADMIN/MANAGER/safety-officer) confirms. Photos in Supabase Storage via photo_paths. Server-side service role access only until production RLS.';
comment on column public.near_miss_reports.report_no is
    'Human-readable report number: YYYYMM + monthly sequence (unique). App computes seq collision-safe; unique constraint is the final backstop.';
comment on column public.near_miss_reports.proposed_grade is
    'Grade proposed by the reporter (S~D, nullable). Not authoritative — evaluator sets confirmed_grade.';
comment on column public.near_miss_reports.confirmed_grade is
    'Grade confirmed by the evaluator (S~D). Present only when status is EVALUATED/CLOSED (see near_miss_eval_consistency).';
comment on column public.near_miss_reports.department_id is
    'Report-time department attribution (FK). Group is derived from the department via 004 group_id at read time — group_id is NOT stored here.';
comment on column public.near_miss_reports.incident_date is
    'Date the near-miss occurred. Period/stats aggregation uses THIS column, not created_at.';
comment on column public.near_miss_reports.photo_paths is
    'JSON array of Supabase Storage object paths (strings). Binary is never stored in the DB.';
comment on column public.near_miss_reports.is_active is
    'Archival flag only. Withdrawal/rejection are represented by status, NOT by flipping this.';

-- =========================================================================
-- 3) 인덱스
-- =========================================================================
-- 처리 대기열: 활성 보고서의 상태별 조회(부분 인덱스로 보존 archive 제외).
create index if not exists near_miss_status_active_idx
    on public.near_miss_reports(status) where is_active;
create index if not exists near_miss_incident_date_idx
    on public.near_miss_reports(incident_date);
create index if not exists near_miss_dept_date_idx
    on public.near_miss_reports(department_id, incident_date);
create index if not exists near_miss_confirmed_grade_idx
    on public.near_miss_reports(confirmed_grade);
create index if not exists near_miss_cause_code_idx
    on public.near_miss_reports(cause_code);
create index if not exists near_miss_reporter_idx
    on public.near_miss_reports(reporter_user_id);

-- 검증용(선택, read-only): 상태 분포 확인.
--   select status, count(*) from public.near_miss_reports group by status;
