-- 010: 업무별 담당 권한(user_capabilities) + 알림 수신 이메일(user_emails).
--
-- 목적 (사용자 지시 2026-08-07):
--   role 3종(ADMIN/MANAGER/USER)만으로는 "숙소관리 담당자", "업무요청 처리 담당자" 같은
--   업무별 담당을 표현할 수 없다. 담당 종류는 앞으로 계속 늘어나므로(숙소·업무요청·…)
--   boolean 컬럼 증설(예: 006 의 users.is_safety_officer)이 아니라 **user↔capability
--   M:N 테이블**로 둔다 — 담당 신설이 migration 없이 코드 등록만으로 끝난다.
--   알림 이메일은 "한 사람이 복수 주소, 업무별로 다른 주소(특정 업무 1개, 다른 업무 2개)"
--   요구라 users 컬럼이 아니라 **행 단위 user_emails(user, email, scope)** 로 정규화한다.
--
-- 순차·의존: 001(users) 이후 언제든. 008/009 와 독립.
--
-- 설계 결정:
--   * capability/scope 는 자유 텍스트 코드(대문자 스네이크, 예: LODGING_OFFICER,
--     WORK_REQUEST_OFFICER). 유효 코드 목록은 앱(modules/config.py)이 소유한다 —
--     DB 는 형식(비공백·대문자 스네이크)만 검증하고 의미를 알지 못한다(007/008 선긋기와 동일).
--   * user_emails.scope 'ALL' = 모든 업무 수신. 특정 업무 코드면 그 업무 알림에만 사용.
--     수신자 계산(담당 capability 보유자의 (ALL ∪ 해당 업무) 이메일)은 앱 계층 소관.
--   * 기존 users.is_safety_officer 는 이번에 이관하지 않는다(안전담당 화면·계약이 참조 중).
--     후속 통합은 BACKLOG 에서 추적.
--
-- 안전 계약 (001~009 관행): guarded DDL(재실행 안전) · no-drop · 기존 행 무기록 ·
-- RLS enable/policy 없음(service role 서버 접근만) · (3) 스키마 assertion.
--
-- 수동 롤백 (역순; 010 이전 데이터 유지):
--   drop trigger if exists user_emails_set_updated_at on public.user_emails;
--   drop table if exists public.user_emails;
--   drop trigger if exists user_capabilities_set_updated_at on public.user_capabilities;
--   drop table if exists public.user_capabilities;

-- =========================================================================
-- 0) 전제 assertion
-- =========================================================================
do $$
begin
    if to_regclass('public.users') is null then
        raise exception '010 전제 위반: public.users 가 없습니다(001 미적용).';
    end if;
    if to_regproc('public.set_updated_at') is null then
        raise exception '010 전제 위반: set_updated_at() 이 없습니다(001 미적용).';
    end if;
end
$$;

-- =========================================================================
-- 1) user_capabilities — 업무별 담당 권한 (user ↔ capability M:N)
-- =========================================================================
create table if not exists public.user_capabilities (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    capability text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    constraint user_capabilities_user_cap_key unique (user_id, capability),
    -- 대문자 스네이크 코드만(공백·소문자·특수문자 차단) — 의미 검증은 앱 소관.
    constraint user_capabilities_cap_format check (capability ~ '^[A-Z][A-Z0-9_]{1,63}$')
);

comment on table public.user_capabilities is
    '업무별 담당 권한(capability) 부여. 코드 의미·유효 목록은 앱(modules/config.py)이 소유. on delete cascade — 담당 부여는 계정 종속 파생 데이터.';

do $$
begin
    if not exists (
        select 1 from pg_trigger
        where tgrelid = 'public.user_capabilities'::regclass
          and tgname = 'user_capabilities_set_updated_at'
    ) then
        create trigger user_capabilities_set_updated_at
            before update on public.user_capabilities
            for each row execute function public.set_updated_at();
    end if;
end
$$;

create index if not exists user_capabilities_cap_idx
    on public.user_capabilities (capability);

alter table public.user_capabilities enable row level security;

-- =========================================================================
-- 2) user_emails — 알림 수신 이메일 (복수, 업무 scope)
-- =========================================================================
-- 회수 의미: user_capabilities 와 대칭으로 **행 단위 부여/삭제**(is_active 없음 —
-- 2026-08-07 recon 조사에서 두 테이블의 회수 의미 비대칭이 지적되어 통일).
-- 일시 수신중지 같은 소프트 상태가 필요해지면 가산적 컬럼 추가로 재도입한다.
create table if not exists public.user_emails (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    email text not null,
    scope text not null default 'ALL',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by text,
    updated_by text,
    -- 최소 형식 검증(@ 와 도메인 점) — 엄밀한 검증·정규화는 앱 계층.
    constraint user_emails_email_format check (email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    constraint user_emails_scope_format check (scope ~ '^[A-Z][A-Z0-9_]{1,63}$')
);

-- 같은 사람·같은 scope 에 같은 주소 중복 금지 — **대소문자 무시**(Discourse user_emails
-- 의 lower(email) 유니크 선례). A@x.com/a@x.com 이중 발송을 DB 가 막는다.
-- 저장 시 소문자 정규화는 앱 계층이 하되, 이 인덱스가 최종 방어선이다.
create unique index if not exists user_emails_user_scope_email_lower_key
    on public.user_emails (user_id, scope, lower(email));

comment on table public.user_emails is
    '알림 수신 이메일. 한 사람이 복수 주소·업무별 상이한 주소 가능. scope=ALL 은 전 업무 수신, 특정 업무 코드는 그 업무만. 수신자 계산은 앱 계층.';

do $$
begin
    if not exists (
        select 1 from pg_trigger
        where tgrelid = 'public.user_emails'::regclass
          and tgname = 'user_emails_set_updated_at'
    ) then
        create trigger user_emails_set_updated_at
            before update on public.user_emails
            for each row execute function public.set_updated_at();
    end if;
end
$$;

create index if not exists user_emails_user_idx on public.user_emails (user_id);
create index if not exists user_emails_scope_idx on public.user_emails (scope);

alter table public.user_emails enable row level security;

-- =========================================================================
-- 3) 스키마 assertion — 부분 적용 묵인 금지
-- =========================================================================
do $$
begin
    if to_regclass('public.user_capabilities') is null then
        raise exception '010 검증 실패: user_capabilities 가 없습니다.';
    end if;
    if to_regclass('public.user_emails') is null then
        raise exception '010 검증 실패: user_emails 가 없습니다.';
    end if;
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.user_capabilities'::regclass
          and conname = 'user_capabilities_user_cap_key'
    ) then
        raise exception '010 검증 실패: user_capabilities 유니크 제약이 없습니다.';
    end if;
    if not exists (
        select 1 from pg_class
        where relname = 'user_emails_user_scope_email_lower_key' and relkind = 'i'
    ) then
        raise exception '010 검증 실패: user_emails lower(email) 유니크 인덱스가 없습니다.';
    end if;
end
$$;
