-- 012: 숙소 예약 — lodgings(숙소 마스터) + lodging_reservations(예약 신청/승인).
--
-- 목적 (사용자 승인 전 DRAFT — 실행/원격 write 금지, Codex 감사 + 사용자 승인 게이트):
--   신규 기능 "숙소 예약 신청 → 승인/반려 → 사용완료"의 데이터 기반.
--   예약 단위는 숙소 1건(단독 점유)이며 호실·정원 개념을 두지 않는다(2026-08-07 사용자
--   결정). 신청 입력은 숙소·체크인·체크아웃 3개뿐이고, 점유 구간은 반개구간
--   [check_in, check_out) 이라 체크아웃 당일 다음 사용자의 체크인이 가능하다.
--   승인 권한은 담당 권한(user_capabilities 의 LODGING_OFFICER)이 결정하며, 이 파일은
--   권한 관련 컬럼을 만들지 않는다 — 담당 저장소는 010 이 이미 제공한다.
--
-- 번호 정합 (docs/database.md §4·§7):
--   005(가칭)는 004 후속 정리로 예약되어 있고 저장소 최신 파일은 011 이다. 숙소 예약은
--   독립 기능이므로 다음 자유 번호인 012 를 쓴다. 파일 번호는 적용 순서일 뿐 적용 여부가
--   아니다 — 적용 상태는 read-only probe 로만 단정한다.
--
-- 안전 계약 (001/006/010 관행 준수):
--   * 어떤 테이블도 drop 하지 않고 기존 행/값을 삭제·덮어쓰지 않는다. 백필 없음.
--   * 재실행 안전: 모든 문장이 guarded (create table/index if not exists,
--     do-block 으로 트리거·제약 존재 확인 후 추가).
--   * 기존 테이블(001~011)은 참조만 하고 수정하지 않는다. 신규 컬럼 추가도 없다.
--   * RLS 는 enable 하되 policy 는 두지 않는다(service role 서버 접근만 — 001/006/010 관행).
--   * (0) 전제 assertion / (5) 종료 assertion 으로 부분 적용을 묵인하지 않는다.
--     특히 겹침 배타 제약은 이 파일과 **같은 트랜잭션**에서 생겨야 한다 — 테이블만
--     적용되고 백스톱이 빠지면 이중 예약을 막을 최종 방어선이 사라진다.
--
-- 수동 롤백 (역순; 012 이전 데이터 유지):
--   drop table if exists public.lodging_reservations;
--   drop table if exists public.lodgings;
--   -- btree_gist 는 다른 기능이 쓸 수 있으므로 자동으로 되돌리지 않는다.

-- =========================================================================
-- 0) 전제 assertion
-- =========================================================================
do $$
begin
    if to_regclass('public.users') is null then
        raise exception '012 전제 위반: public.users 가 없습니다(001 미적용).';
    end if;
    if to_regclass('public.departments') is null then
        raise exception '012 전제 위반: public.departments 가 없습니다(001 미적용).';
    end if;
    if to_regproc('public.set_updated_at') is null then
        raise exception '012 전제 위반: set_updated_at() 이 없습니다(001 미적용).';
    end if;
end
$$;

-- =========================================================================
-- 1) lodgings — 숙소 마스터(예약 단위 = 숙소 1건, 단독 점유)
-- =========================================================================
-- 미사용 컬럼(room_no/lodging_type/capacity)은 만들지 않는다(2026-08-20 결정):
-- 예약 흐름·화면 어디에서도 쓰지 않고, 유형 check 제약은 실제 숙소(대관령·태안)를
-- 잘못 강제한다. 필요해지면 add column if not exists 로 가산 추가한다.
create table if not exists public.lodgings (
    id            bigint generated by default as identity primary key,
    lodging_code  text not null unique,           -- 자연키. 예: 'DAEGWALLYEONG'
    lodging_name  text not null,                  -- 화면 표기명(대관령 · 태안)
    location      text not null default '',       -- 소재지(표시용)
    sort_order    integer not null default 0,
    is_active     boolean not null default true,  -- 소프트 삭제(신규 신청 대상에서 제외)
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    created_by    text,
    updated_by    text,
    -- 코드 형식만 DB 가 본다. 의미·유효 목록은 앱 소관(010 capability 관행과 동일 선긋기).
    constraint lodgings_code_format    check (lodging_code ~ '^[A-Z][A-Z0-9_-]{1,63}$'),
    constraint lodgings_name_not_blank check (btrim(lodging_name) <> '')
);

do $$
begin
    if not exists (
        select 1 from pg_trigger
        where tgrelid = 'public.lodgings'::regclass
          and tgname = 'lodgings_set_updated_at'
    ) then
        create trigger lodgings_set_updated_at
            before update on public.lodgings
            for each row execute function public.set_updated_at();
    end if;
end
$$;

alter table public.lodgings enable row level security;

comment on table public.lodgings is
    '숙소 마스터. 예약 단위 = 숙소 1건(단독 점유, 호실·정원 개념 없음). 화면은 lodging_name 만 표기하고 lodging_code 를 자연키로 쓴다.';
comment on column public.lodgings.lodging_code is
    'Natural key used by the app/facade (screens never see DB ids). Uppercase snake/hyphen code.';
comment on column public.lodgings.is_active is
    'Soft delete. false 면 신규 신청 대상에서 제외되지만 기존 예약은 보존된다(참조 무결성 유지).';

-- =========================================================================
-- 2) lodging_reservations — 예약 신청/승인
-- =========================================================================
create table if not exists public.lodging_reservations (
    id                 bigint generated by default as identity primary key,

    -- request_no: 'LDG-' + 연월(YYYYMM) + '-' + 월별 순번(zero-pad 3). 예: 'LDG-202608-001'.
    --   충돌 안전 생성: 앱이 대상 연월의 최대 순번 +1 로 계산하고, 아래 unique 제약을
    --   최종 방어선으로 삼아 동시 삽입 시 unique_violation(23505)을 받아 재채번·재시도한다
    --   (006 report_no 와 같은 계약).
    request_no         text not null unique,

    -- 사람/조직/숙소 관계값(ID/FK). 화면 자연키(emp_no/dept_code/lodging_code)는 파사드 조인.
    lodging_id         bigint not null references public.lodgings(id)  on delete restrict,
    applicant_user_id  bigint not null references public.users(id)     on delete restrict,
    department_id      bigint references public.departments(id),       -- 신청 시점 소속 스냅샷

    check_in           date not null,
    check_out          date not null,                    -- 반개구간 [check_in, check_out)

    status             text not null default 'REQUESTED',
    decided_by_user_id bigint references public.users(id) on delete restrict,
    decided_at         timestamptz,
    decision_comment   text not null default '',

    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now(),
    created_by         text,
    updated_by         text,

    constraint lodging_res_status_chk
        check (status in ('REQUESTED','APPROVED','REJECTED','CANCELLED','COMPLETED')),
    constraint lodging_res_period_chk check (check_out > check_in),
    -- 처리 흔적 정합: 신청 상태에는 처리 흔적이 없고, 처리된 상태에는 처리자·시각이 모두
    -- 있다(006 near_miss_eval_consistency 와 같은 취지 — 부분 처리 상태 방지).
    constraint lodging_res_decision_consistency check (
        case
            when status = 'REQUESTED'
                then decided_by_user_id is null and decided_at is null
            else decided_by_user_id is not null and decided_at is not null
        end
    ),
    -- 반려는 사유를 요구한다(앱의 '반려 사유 필수'와 같은 문장을 DB 에서도 강제).
    constraint lodging_res_reject_reason_chk
        check (status <> 'REJECTED' or btrim(decision_comment) <> '')
);

do $$
begin
    if not exists (
        select 1 from pg_trigger
        where tgrelid = 'public.lodging_reservations'::regclass
          and tgname = 'lodging_reservations_set_updated_at'
    ) then
        create trigger lodging_reservations_set_updated_at
            before update on public.lodging_reservations
            for each row execute function public.set_updated_at();
    end if;
end
$$;

alter table public.lodging_reservations enable row level security;

create index if not exists idx_lodging_res_lodging_period
    on public.lodging_reservations (lodging_id, check_in, check_out);
create index if not exists idx_lodging_res_applicant
    on public.lodging_reservations (applicant_user_id, status);
create index if not exists idx_lodging_res_status
    on public.lodging_reservations (status, check_in);

comment on table public.lodging_reservations is
    'Lodging reservations. Occupancy is the half-open range [check_in, check_out) so a same-day handover is allowed. Applicant/decider names are NOT stored — the facade joins users at read time.';
comment on column public.lodging_reservations.request_no is
    'Human-readable reservation number LDG-YYYYMM-NNN (monthly sequence, unique). App computes it collision-safe; the unique constraint is the final backstop.';
comment on column public.lodging_reservations.department_id is
    'Applicant department at request time (FK). Group is derived from the department at read time — group_id is NOT stored here (006 관행).';
comment on column public.lodging_reservations.decision_comment is
    'Approve/reject/cancel comment. Must be non-blank when status is REJECTED (lodging_res_reject_reason_chk).';

-- =========================================================================
-- 3) 중복(겹침) 예약 차단 백스톱 — 배타 제약
-- =========================================================================
-- 앱은 신청·수정·승인 시점에 겹침을 미리 검사하지만(1·2차), 동시 커밋 경합은 앱 검사만으로
-- 막을 수 없다. 살아있는 상태(신청·승인·사용완료)끼리 같은 숙소·겹치는 기간을 금지하는
-- 배타 제약이 최종 방어선이다. 반려·취소는 점유가 아니므로 제외한다.
-- btree_gist 는 bigint 동등비교(lodging_id WITH =)를 GiST 로 다루기 위해 필요하다.
create extension if not exists btree_gist;

-- alter table ... add constraint 에는 if not exists 가 없다 → 존재 확인 후 추가(재실행 안전).
do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.lodging_reservations'::regclass
          and conname = 'lodging_res_no_overlap'
    ) then
        alter table public.lodging_reservations
            add constraint lodging_res_no_overlap
            exclude using gist (
                lodging_id WITH =,
                daterange(check_in, check_out, '[)') WITH &&
            ) where (status in ('REQUESTED','APPROVED','COMPLETED'));
    end if;
end
$$;

comment on constraint lodging_res_no_overlap on public.lodging_reservations is
    'Overlap backstop: no two live reservations (REQUESTED/APPROVED/COMPLETED) may share a lodging and an overlapping half-open date range. Violations surface as SQLSTATE 23P01 and the app translates them into the "already reserved" message.';

-- =========================================================================
-- 4) (의도적으로 비움) 시드 없음
-- =========================================================================
-- 숙소 마스터 행은 이 파일에서 넣지 않는다. 실데이터 입력은 migration 이 아니라 별도
-- 승인된 작업이다(백필·seed 금지 계약). sample 모드는 앱의 sample 시드를 쓴다.

-- =========================================================================
-- 5) 스키마 assertion — 부분 적용 묵인 금지
-- =========================================================================
do $$
begin
    if to_regclass('public.lodgings') is null then
        raise exception '012 검증 실패: lodgings 가 없습니다.';
    end if;
    if to_regclass('public.lodging_reservations') is null then
        raise exception '012 검증 실패: lodging_reservations 가 없습니다.';
    end if;
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.lodging_reservations'::regclass
          and conname = 'lodging_res_decision_consistency'
    ) then
        raise exception '012 검증 실패: 처리 흔적 정합 제약이 없습니다.';
    end if;
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.lodging_reservations'::regclass
          and conname = 'lodging_res_no_overlap'
    ) then
        raise exception '012 검증 실패: 예약 겹침 배타 제약이 없습니다(중복 차단 백스톱 부재).';
    end if;
    if not exists (
        select 1 from pg_trigger
        where tgrelid = 'public.lodging_reservations'::regclass
          and tgname = 'lodging_reservations_set_updated_at'
    ) then
        raise exception '012 검증 실패: updated_at 트리거가 없습니다.';
    end if;
end
$$;
